name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ['3.10', '3.11']
        
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        
    - name: Start Ollama Service
      run: |
        ollama serve &
        sleep 10  # Give ollama time to start
        
    - name: Pull Required Model
      run: |
        ollama pull deepseek-r1
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .  # This will install all dependencies from pyproject.toml
        
    - name: Run tests
      run: |
        pytest tests/ -v